{
 "title": "Serbian Protests -- Media Sentiment Overview",
 "description": "This dashboard shows the data gathered from various pro-government and independent news sources on the topic of ongoing Serbian student-led protests.",
 "tags": [
  "protest",
  "UN SDG 16",
  "freedom",
  "justice",
  "activism"
 ],
 "time": { "from": "2025-01-31T23:00:00.000Z", "to": "2025-05-02T22:00:00.000Z" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 24, "w": 18, "x": 0, "y": 0 },
   "options": {
    "content": "# <p style=\"text-align: center;\"><span style=\"color: #4dbbff;\">🚶‍♂️☮️ Peaceful Protests Tracker:</span> <span style=\"color: #ffa75a;\">Headlines vs Reality</span> 📰<span style=\"font-size:0.9em;\">⚖️</span>✨</p>\n\n<p style=\"text-align: center;\">\n<span style=\"font-size:1.35em; color:#5e17eb; font-family: 'Monaco', monospace; letter-spacing: 1px; text-transform: uppercase;\">Unveiling Media Narratives on the Serbian Protests</span>\n</p>\n\n___\n**What happens when tragedy strikes, justice stalls, and the people take to the streets?**\n\nIn Serbia, following the tragic Novi Sad railway canopy collapse where 16 lives were lost, widespread student-led protests erupted, demanding **accountability and institutional integrity** – the very heart of **UN Sustainable Development Goal 16 (Peace, Justice & Strong Institutions)**.\n\nBut in a polarized media landscape, what's the real story?\n\n**Enter our project:** We built a pipeline to cut through the noise.\n\nHere's the breakdown of the powerful tech stack we've engineered:\n\n*   <span style=\"background-color: lightblue; color: navy; font-weight: bold; padding: 2px;\">Web Scraping Engine (Python & BeautifulSoup):</span> \nWe deploy **Python's BeautifulSoup** to meticulously scrape news from both pro-government *and* independent media outlets.\n\n*   <span style=\"background-color: lightblue; color: navy; font-weight: bold; padding: 2px;\">AI Insight Core (Gemini 2.5 Flash API):</span> \nThis raw data feeds into our smart AI core, powered by **Gemini 2.5 Flash**, extracting key facts, locations, participant mentions, and crucial *sentiment analysis* – how are protestors and their demands portrayed?\n\n*   <span style=\"background-color: lightblue; color: navy; font-weight: bold; padding: 2px;\">Automated Data Pipeline (Spring Cron-Based Backend):</span> \nA robust **Cron-based Spring backend** ensures this data stream is refreshed *hourly*, providing near real-time insights.\n\n*   <span style=\"background-color: lightblue; color: navy; font-weight: bold; padding: 2px;\">Scalable Cloud Storage (MongoDB Atlas):</span> \nAll structured insights are securely stored in **MongoDB Atlas**.\n\n*   <span style=\"background-color: lightblue; color: navy; font-weight: bold; padding: 2px;\">Dynamic Visualization Suite (Grafana):</span>\nFinally, **Grafana** takes center stage! We use its powerful visualization tools to paint a clear, visually striking picture – comparing narratives, tracking sentiment shifts, mapping protest activity, and revealing the contrasting realities presented to the public.\n\n![Serbian protest image](https://www.news10.com/wp-content/uploads/sites/64/2025/01/67988ec4d3ab84.86169358.jpeg?w=960&h=540&crop=1)"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 5, "x": 18, "y": 0 },
   "options": {
    "content": "![alt text](https://agenda2030lac.org/sites/default/files/styles/256x256/public/2019-08/E_SDG%20goals_icons-individual-rgb-16_0.png?itok=E7j2iDIR)"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 15, "w": 5, "x": 18, "y": 8 },
   "options": {
    "content": "![alt text](https://attck.com/wp-content/uploads/11.01-ATTCK-Case-study-Mobile-Hero-United-Nations-1.jpg)"
   }
  },
  {
   "title": "Locations of the protests in Serbia in the past selected period",
   "type": "geomap",
   "description": "Bigger bubble -- bigger protest size. Click on the map for informative interactive points.",
   "gridPos": { "h": 17, "w": 13, "x": 0, "y": 24 },
   "targets": [
    { "parsedQuery": "db.protests.find()", "query": "db.protests.find()" }
   ]
  },
  {
   "title": "Table of past and planned protests",
   "type": "table",
   "description": "Note: S&O means Students and Other organizers",
   "gridPos": { "h": 17, "w": 11, "x": 13, "y": 24 },
   "targets": [
    {
     "parsedQuery": "db.protests.aggregate([{\"$project\":{\"_id\":0,\"date\":1,\"location\":1,\"organizer\":1,\"count.government\":1,\"count.independent\":1}}])",
     "query": "db.protests.aggregate([\r\n  {\r\n    $project: {\r\n      _id: 0,\r\n      date: 1,\r\n      location: 1,\r\n      organizer: 1,\r\n      \"count.government\": 1,\r\n      \"count.independent\": 1\r\n    }\r\n  }\r\n])"
    }
   ]
  },
  {
   "title": "Goverment vs Independent media protest coverage comparison",
   "type": "timeseries",
   "description": "We can spot a big discrepancy in the data sources, leading us to conclude that one or both of the sides are biased. ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "parsedQuery": "db.days.find({}, {\"x\":0,\"y\":0})",
     "query": "db.days.find(\r\n  {},\r\n  { x: 0, y: 0 }\r\n)"
    }
   ]
  },
  {
   "title": "Student mentions in media",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parsedQuery": "db.days.aggregate([{\"$group\":{\"_id\":\"$studentMentions.independent\",\"total_good\":{\"$sum\":\"$studentMentions.goodCount\"},\"total_bad\":{\"$sum\":\"$studentMentions.badCount\"}}}])",
     "query": "db.days.aggregate([\r\n \r\n  {\r\n    \"$group\": {\r\n      \"_id\": \"$studentMentions.independent\",\r\n      \"total_good\": { \"$sum\": \"$studentMentions.goodCount\" },\r\n      \"total_bad\": { \"$sum\": \"$studentMentions.badCount\" }\r\n    }\r\n  }\r\n\r\n])"
    }
   ]
  },
  {
   "title": "State Mentions in media",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parsedQuery": "db.days.aggregate([{\"$group\":{\"_id\":\"$studentMentions.independent\",\"total_good\":{\"$sum\":\"$stateMentions.goodCount\"},\"total_bad\":{\"$sum\":\"$stateMentions.badCount\"}}}])",
     "query": "db.days.aggregate([\r\n \r\n  {\r\n    \"$group\": {\r\n      \"_id\": \"$studentMentions.independent\",\r\n      \"total_good\": { \"$sum\": \"$stateMentions.goodCount\" },\r\n      \"total_bad\": { \"$sum\": \"$stateMentions.badCount\" }\r\n    }\r\n  }\r\n\r\n])"
    }
   ]
  },
  {
   "title": "Goverment vs Independent protest attendance estimations",
   "type": "timeseries",
   "description": "We can spot a big discrepancy in the data sources, leading us to conclude that one or both of the sides are biased. ",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "parsedQuery": "db.protests.find({}, {\"x\":0,\"y\":0})",
     "query": "db.protests.find(\r\n  {},\r\n  { x: 0, y: 0 }\r\n)"
    }
   ]
  },
  {
   "title": "Average independent sources protest attendance estimations",
   "type": "stat",
   "description": "We can spot a big discrepancy in the data sources, leading us to conclude that one or both of the sides are biased. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parsedQuery": "db.protests.find({}, {\"x\":0,\"y\":0})",
     "query": "db.protests.find(\r\n  {},\r\n  { x: 0, y: 0 }\r\n)"
    }
   ]
  },
  {
   "title": "Average goverment protest attendance estimations",
   "type": "stat",
   "description": "We can spot a big discrepancy in the data sources, leading us to conclude that one or both of the sides are biased. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parsedQuery": "db.protests.aggregate([{\"$group\":{\"_id\":null,\"averageValue\":{\"$avg\":\"$count.government\"}}}])",
     "query": "db.protests.aggregate([\r\n  {\r\n    $group: {\r\n      _id: null,\r\n      averageValue: { $avg: \"$count.government\" }\r\n    }\r\n  }\r\n])"
    }
   ]
  }
 ]
}